### ISSUE TITLE
VAChT_feobv_hc3 nifti data?

### ISSUE THREAD

**Issue by TingsterX** [netneurolab/hansen_receptors#2]
Hey there,

Thanks for sharing this fantastic work!

I noticed that the nifti data of VAChT_feobv_hc3_spreng is missing in the PET_nifti_images. Do you mind sharing it as well? Thank you!

Best,
Ting

**Comment by justinehansen** [comment]
Hi Ting,

Thanks for reaching out! Unfortunately that one FEOBV map is not yet publicly available :slightly_frowning_face: 
The good news is that it's highly correlated with the other three FEOBV maps, so feel free to use any of the other three, or create a composite weighted average as I do, but simply remove VAChT_feobv_hc3_spreng from the list. Let me know if there's anything else I can help with!

Best,
Justine
