### ISSUE TITLE
one of PET images is missing.

### ISSUE THREAD

**Issue by lanshanxuying** [netneurolab/hansen_receptors#5]
Dear professor Hansen，
      Thank you for sharing!
      I found that a PET image used in your code name as "VAChT_feobv_hc3_spreng", does not seem to have been uploaded to the GitHub project. Is it that you no longer use this image file in your subsequent research? Or did you accidentally forget to upload it? If you forgot, could you please upload this image file? Thank you again for sharing.

**Comment by justinehansen** [comment]
Hi @lanshanxuying, thanks for reaching out. `VAChT_feobv_hc3_spreng` is unfortunately not openly available yet (see Issue #2), but the other three FEOBV maps are all good alternatives. They're all highly correlated to one another so you can either use one of the other three, or combine the three in a weighted average. Sorry about that!

Justine

**Comment by lanshanxuying** [comment]
Thank you for your reply !
