### ISSUE TITLE
Data on Desikan–Killiany atlas

### ISSUE THREAD

**Issue by Dr-Chen-Xiaoyu** [netneurolab/hansen_receptors#8]
Hi,

I want to use the PET maps for each neurotransmitter based on Desikan–Killiany atlas. I guess the data I want is in the folder "hansen_receptors/data/PET_parcellated/scale033/". However, these excel files all have 83 columns, not matched to the 68 regions of Desikan–Killiany. Maybe provide the notations of parcellation for each column ?

Best,
Xiaoyu

**Comment by justinehansen** [comment]
Hi, the names of the regions in order can be found [here](https://github.com/netneurolab/hansen_receptors/blob/main/data/lausanne/region_info_scale033.xlsx).
Note that although the regions are the same as in the DK atlas, the ordering is different (according to the Cammoun/Lausanne atlas).

**Comment by Dr-Chen-Xiaoyu** [comment]
Thanks!
